# IMDS Computer Workshop 8  
### *By Jeffrey Giansiracusa - Michaelmas 2023*

---

This worksheet covers the content of lectures

    (some material from last week's videos)
    7.4 Inverse transformations
    7.5 Determinants
    
    (and some content from this week's videos)
    8.1 Eigenvectors
    8.2 Eigen examples
    8.3 Changing basis

Key ideas to learn:

* How to check if a matrix $B$ is the inverse of a matrix $A$. 
* Idea of how linear transformations change area/volume by a factor given by the determinant.
* Determinant facts: $\det AB = (\det A)(\det B)$. How to calculate a $2\times 2$ determinant. Swapping rows or columns changes the determinant by a sign.
* Key Fact: The determinant is nonzero if and only if the matrix is invertible.
* Be able to convert vectors from one basis to another.
* Know the definition of eigenvectors and eigenvalues and how to get the computer to find them.

# Initialization code to run before you start your work

Click on the cell below and then type Shift-Return to execute it.

In [1]:
import numpy as np
import math

from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt

from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()
 
# Draws a polygon in the xy-plane if you give it a list [[x1,y1], [x2,y2], ... ] of coordinates of the verties   
def Plot2dPolygon(list_of_vertices):   
    p = figure(plot_width=400, plot_height=400, title="Polygon")
    xcoords = [list_of_vertices[i][0] for i in range(len(list_of_vertices))] + [list_of_vertices[0][0]]
    ycoords = [list_of_vertices[i][1] for i in range(len(list_of_vertices))] + [list_of_vertices[0][0]]
    p.line(xcoords, ycoords, line_width=2)
    show(p)
    
# Input is a list of 2d vectors to be plotted.
def Plot2dVectors(list_of_endpoints):   
    p = figure(width=400, height=400, title="Vectors!")
    for vect in list_of_endpoints:
        xcoords = [0,vect[0]]
        ycoords = [0,vect[1]]
        p.line(xcoords, ycoords, line_width=2)
        p.circle([vect[0]], [vect[1]], color='red', size=2)
    show(p)

# Input is a list of 2d vectors as (x,y) coordinates of points to be plotted.
def Plot2dDots(list_of_points):   
    TOOLTIPS = [("(x,y)", "($x, $y)")]
    p = figure(width=600, height=600, title="Some points",tooltips=TOOLTIPS)
    D = np.array(list_of_points).T
    p.circle(D[0], D[1], color='blue', size=6)
    show(p)
    
        
# Input is a list of 3d vectors
def Plot3dVectors(list):
    plt.figsize(6,4)
    ax = plt.axes(projection = '3d')
    for vect in list:
        ax.plot([0,vect[0]], [0,vect[1]], [0,vect[2]],color='blue')
    ax.plot([0,0], [-10,10], [0,0], 'g--')
    ax.plot([-10,10], [0, 0], [0,0], 'g--')
    ax.plot([0,0], [0, 0], [-10,10], 'g--')
    plt.draw()
    plt.show()    

def Plot3dDots(list):       
    limit=20
    plt.figure(figsize=(10, 8), dpi=80)
    ax = plt.axes(projection = '3d')
    ax.set_xlim(-limit,limit)
    ax.set_ylim(-limit,limit)
    ax.set_zlim(-limit,limit)

    # Draw the shadow
    ax.scatter3D([item[0] for item in list], [item[1] for item in list], [-20 for item in list], color='grey')

    # Draw the coordinate axes
    ax.plot([0,0], [-limit,limit], [0,0], 'g--')
    ax.plot([-limit,limit], [0, 0], [0,0], 'g--')
    ax.plot([0,0], [0, 0], [-limit,limit], 'g--')

    # Now draw the points
    ax.scatter3D([item[0] for item in list], [item[1] for item in list], [item[2] for item in list], c=[item[2] for item in list])

    plt.draw()
    plt.show()    


def Trans(vect):
    Eigenvects = np.array( [[1, 2, 4], [-1, 0, 3], [0,1,0]] ).T
    Eigenvalues = np.array([2,3,-1])
    result = Eigenvects @ np.diag(Eigenvalues) @ np.linalg.inv(Eigenvects) @ vect
    return result




Loading BokehJS ...

# Exercise 1

1. Check if the matrix $A = \begin{pmatrix} 1 & 2 \\ -2 & 1\end{pmatrix}$ has the matrix $B = \begin{pmatrix} 0.2 & -0.4 \\ 0.4 & 0.2\end{pmatrix}$ as its inverse.
2. Use **np.linalg.inv(..)** to find the inverse of the matrix $C = \begin{pmatrix} 1 & 2 & 0 \\ 0 & -2 & 1 \\ 1 & -1 & 0\end{pmatrix}$.
3. Try to find the inverse of $D = \begin{pmatrix} 1 & 2 & 0 \\ 0 & -2 & 1 \\ 1 & 0 & 1\end{pmatrix}$ (Look carefully - this matrix is only very slightly different from $C$).
4. What are the ranks of $A,B,C,D$?
5. What are the determinants of these matrices?  You can use **np.linalg.det(A)**


In [2]:
# You can write code here if you want.

import numpy as np

# Exercise 1

# 1. Check if A has B as its inverse
A = np.array([[1, 2], [-2, 1]])
B = np.array([[0.2, -0.4], [0.4, 0.2]])
is_inverse = np.allclose(np.dot(A, B), np.eye(2)) and np.allclose(np.dot(B, A), np.eye(2))
print(f"Is B the inverse of A? {is_inverse}")

# 2. Find the inverse of C
C = np.array([[1, 2, 0], [0, -2, 1], [1, -1, 0]])
inverse_C = np.linalg.inv(C)
print(f"Inverse of C:\n{inverse_C}")

# 3. Try to find the inverse of D
D = np.array([[1, 2, 0], [0, -2, 1], [1, 0, 1]])
try:
    inverse_D = np.linalg.inv(D)
    print(f"Inverse of D:\n{inverse_D}")
except np.linalg.LinAlgError:
    print("Matrix D is singular; it does not have an inverse.")

# 4. Ranks of A, B, C, D
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_C = np.linalg.matrix_rank(C)
rank_D = np.linalg.matrix_rank(D)
print(f"Rank of A: {rank_A}, Rank of B: {rank_B}, Rank of C: {rank_C}, Rank of D: {rank_D}")

# 5. Determinants of A, B, C, D
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
print(f"Determinant of A: {det_A}, Determinant of B: {det_B}, Determinant of C: {det_C}, Determinant of D: {det_D}")


Is B the inverse of A? True
Inverse of C:
[[ 0.33333333  0.          0.66666667]
 [ 0.33333333 -0.         -0.33333333]
 [ 0.66666667  1.         -0.66666667]]
Matrix D is singular; it does not have an inverse.
Rank of A: 2, Rank of B: 2, Rank of C: 3, Rank of D: 2
Determinant of A: 5.000000000000001, Determinant of B: 0.2, Determinant of C: 3.0000000000000004, Determinant of D: 0.0


--- 

# Exercise 2


0.  What is the area of the square with vertices at 
$$\begin{pmatrix}0 \\ 0\end{pmatrix},\quad \begin{pmatrix} 1 \\ 0 \end{pmatrix}, \quad \begin{pmatrix} 0 \\ 1 \end{pmatrix}, \quad \begin{pmatrix} 1 \\ 1 \end{pmatrix}?$$

1.  Now consider the parallelogram in $\mathbb{R}^2$ with vertices 
$$\begin{pmatrix} 0 \\ 0\end{pmatrix}, \quad \vec{a} = \begin{pmatrix} 2 \\ 5 \end{pmatrix}, \quad \vec{b}=\begin{pmatrix} 3 \\ 1\end{pmatrix}, \quad \vec{c} = \vec{a} + \vec{b}.$$ 
What is the area of this parallelogram?  Hint: can you find a linear transformation that sends the square to this parallelogram?

2.  What is the area of the parallelogram with vertices at the origin, $A\vec{a}, A\vec{b}$, and $A(\vec{a}+\vec{b}),$ where $A$ is the linear transformation given by the matrix $\begin{pmatrix}4 & -1 \\ 2 & 1\end{pmatrix}$?


Hint:  Think about determinants of matrices...  A plotting function **Plot2dPolygon()** has been provided to help you visualise things in this exercise.


In [ ]:
# Here is some code to get you started.  
# The Plot2dPolygon(..) function is provided for your convenience.  
# It takes as input a list of vectors: [vertex1, vertex2, ...]

origin = np.array([0,0])
a = np.array([2,5])
b = np.array([3,1])
c = a + b 

# Plot the unit square
Plot2dPolygon([origin,np.array([1,0]),np.array([1,1]),np.array([0,1]), origin])

# Plot the parallelogram with corners at the origin, a, b, and a+b
Plot2dPolygon([origin,a,c,b])

# Here is the matrix of the linear transformation for part 2.
A = np.array([[4, -1], [2,1]])




---

# Exercise 3

When we write vectors, by default we are writing them with respect to the **standard basis**.
E.g., $\begin{pmatrix} 4 \\ 5 \end{pmatrix} = 4 \vec{e}_1 + 5 \vec{e}_2$.

1.  Check that the vectors $\vec{f}_1 = \begin{pmatrix} 1 \\ 1\end{pmatrix}$ and $\vec{f}_2 = \begin{pmatrix} 1 \\ -1\end{pmatrix}$ are a basis for $\mathbb{R}^2$.  You can do this by making a making a matrix with these vectors as its column and then looking at its determinant.

2.  Write the vector $\begin{pmatrix} 4 \\ 5 \end{pmatrix}$ as a linear combination of $\vec{f}_1$ and $\vec{f}_2$. I.e., find numbers $a_1, a_2$ such that $a_1 \vec{f}_1 + a_2 \vec{f}_2 = \begin{pmatrix} 4 \\ 5 \end{pmatrix}$.  You can do this by making a matrix $F$ with the $\vec{f}_i$ as its columns and then thinking about the equation
$$
F \begin{pmatrix} a_1 \\ a_2 \end{pmatrix} = \begin{pmatrix} 4 \\ 5\end{pmatrix}.
$$
Multiplying both sides of this equation by the inverse of $F$ might be useful.


3. Now in 3d.  
    1. Check that the vectors
    $$\vec{g}_1 = \begin{pmatrix} 2 \\ 0 \\ 1 \end{pmatrix}, \quad \vec{g}_2 = \begin{pmatrix} 0 \\ 3 \\ -1 \end{pmatrix}, \text{ and } \vec{g}_3 = \begin{pmatrix} 0 \\ -2 \\ 2 \end{pmatrix}$$
    are a basis for $\mathbb{R}^3$.
    2. Write the vector $\begin{pmatrix} 10 \\ 10 \\ 10\end{pmatrix}$ as a linear combination of the $\vec{g}_i$ vectors.
    3. Write the vector $\begin{pmatrix} 20 \\ 20 \\ 20\end{pmatrix}$ as a linear combination of the $\vec{g}_i$ vectors.
    2. Write the vector $\begin{pmatrix} 10 \\ -10 \\ -10\end{pmatrix}$ as a linear combination of the $\vec{g}_i$ vectors.



In [ ]:
# Write some code here for Problem 3


---

# Exercise 4

1.  A linear transformation $Trans: \mathbb{R}^3 \to \mathbb{R}^3$ has been defined for you.  You can use it on various vectors, but you don't know the formula.
    1. Determine if each of the vectors $\begin{pmatrix}1 \\ 2\\ 3\end{pmatrix}$ and $\begin{pmatrix}-1 \\ 0\\ 2\end{pmatrix}$ is an eigenvector, and if so, find the corresponding eigenvalues.
    2. What about the vectors $\begin{pmatrix}2 \\ 4\\ 6\end{pmatrix}$ and $\begin{pmatrix} -8 \\ 0\\ 16\end{pmatrix}$?
    
2. Using **np.linalg.det(..)** (but *not* **np.linalg.eig(..)**), determine which of the numbers $\{1,2,3,4,5\}$ are eigenvalues of the matrix $$A = \begin{pmatrix}
4.63414634 & -1.46341463 & 0.29268293 \\
-0.68292683 &  2.26829268 & 0.14634146 \\
-0.12195122 & -0.48780488 & 3.09756098
\end{pmatrix}.$$

3. Consider the matrix $B = \begin{pmatrix} 7 & 0 & -3 \\ -9 & -2 & 3 \\ 18 & 0 & -8\end{pmatrix}$. 
    1. Use **np.linalg.eig(B)** to find the eigenvectors and eigenvalues of $B$.  Is -2 an eigenvalue?  
    2. What number do you get when you multiply all of the eigenvalues together?  
    3. What is the determinant of $B$?  Compare with the product of the eigenvalues.



In [ ]:
# Part 1
# The mystery linear transformation is Trans(..)  E.g. 
print(Trans([1,2,3]))

# Part 2
A = np.array([[ 4.63414634, -1.46341463,  0.29268293],
              [-0.68292683,  2.26829268,  0.14634146],
              [-0.12195122, -0.48780488,  3.09756098]])

# Part 3
B = np.array([[7,0,-3],
              [-9,-2,3],
              [18,0,-8]])


---

# Exercise 5

In this problem you will learn how to make a matrix with a particular set of eigenvalues and eigenvectors.

1. Make a matrix $B$ that gives a linear transformation $\mathbb{R}^3 \to \mathbb{R}^3$ sending the standard basis vectors $\mathbf{e}_1, \mathbf{e}_2, \mathbf{e}_3$ to the vectors 
$$\vec{f_1} = \begin{pmatrix} 5 \\ 6 \\ 1\end{pmatrix}, \quad
\vec{f_2} = \begin{pmatrix} 1 \\ -5 \\ 1\end{pmatrix}, \quad
\vec{f_3} = \begin{pmatrix}0 \\ -2 \\ 1 \end{pmatrix}$$.

2. Now make a matrix $C$ that does the opposite, sending the vectors $\vec{f}_i$ to the standard basis vectors $\vec{e}_i$.

3. Make a matrix $D$ that has the standard basis vectors $\vec{e}_i$ as eigenvectors with eigenvalues $1, 4$ and $10$.

4. By multiplying these matrices together, make a linear tranformation that sends the $\vec{f}_i$ to the standard basis vectors, scales them by the given eigenvalues, and then transforms them back to the $\vec{f}_i$.

5. Using **np.linalg.eig(..)**, check that you matrix does indeed have the desired eigenvectors and eigenvalues.  Note that this function will automatically give you normalized eigenvectors.

6. Bonus:  Can you make a matrix that has the same eigenvalues, but now has eigenvectors
$$\vec{g_1} = \begin{pmatrix} 5 \\ 6 \\ 1\end{pmatrix}, \quad 
  \vec{g_2} = \begin{pmatrix} 1 \\ -5 \\ 1\end{pmatrix}, \quad
  \vec{g_3} = \begin{pmatrix} 4 \\ 11 \\ 0 \end{pmatrix}?$$


In [ ]:
# Write some code here

f1 = np.array([5, 6, 1])
f2 = np.array([1, -5, 1])
f3 = np.array([0, -2, 1])

---

# Exercise 6 (optional)   

*Some conceptual questions*

1.  The determinant of a matrix $A$ is 0.  What does this tell you about its eigenvalues?
2.  The rank of a $3\times 3$ matrix $B$ is 2.  What does this tell you about its eigenvalues?  Think about the rank as the dimension of the range.

*A bit of review/challenge*

3. Consider the matrix $A = 
\begin{pmatrix}
1  &  2  & 5  & 1 \\
2  &  1  & 4  & 5 \\
2  &  5  & 12 & 1 \\
-1 &  1  & 1  & -4
\\\end{pmatrix}$
and the vectors $\vec{u} = \begin{pmatrix} 9 \\ 12 \\ 20 \\ -3 \end{pmatrix}$
and $\vec{v} = \begin{pmatrix} 4 \\ 0 \\ 6 \\ 5 \end{pmatrix}$.
  1. Determine if $A \vec{x} = \vec{u}$ has a solution.  If so, find one.
  2. Determine if $A \vec{x} = \vec{v}$ has a solution.  If so, find one.



